### ISSUE TITLE
Chords are misaligned

### ISSUE THREAD

**Issue by chaptergy** [igrek51/android-songbook#10]
Hello,
first of all thank you for the nice app and all the work you put into it! 

I have noticed, that sometimes the chords are misaligned even though they are specified at certain locations within the text. For example this:

```
[C] Shall [Em] I [Am] stay, would it [F] be [C] a [G] sin?
If [F] I [G] can't [Am] help [F] falling in [C] love [G] with [C] you
```
Is displayed as 
![image](https://user-images.githubusercontent.com/26956711/153752815-79def5e6-d669-46d3-9528-3b721b1da6dc.png)

Towards the ends of the line the cords are displayed way too far to the right, even though there would be plenty of space for them to be at the correct locations. Not really sure why it would wrap the `you` into the next line either.

**Comment by chaptergy** [comment]
It looks like the position of the chord is rendered while the chord is still part of the text, but then the text is reflowed without the chords, which causes this misalignment.

![chords](https://user-images.githubusercontent.com/26956711/153754403-fabfa3fa-9b04-4b46-ab9e-eca3cd36c567.jpg)

**Comment by igrek51** [comment]
That's interesting. I was fighting with it some time ago, but I hoped it was already solved. What app version do you have installed?

It works fine on my device:
![chords](https://user-images.githubusercontent.com/12595017/153895565-3c0265a3-e279-4375-b8e7-413cec58e48d.png)
though I know that measuring text width in Android may act unpredictably (unfortunately this line may give different results https://github.com/igrek51/android-songbook/blob/master/app/src/main/java/igrek/songbook/chords/lyrics/LyricsInflater.kt#L53)

**Comment by chaptergy** [comment]
I'm on application version `v1.19.1 (1829)`. On a Pixel 4a with Android 12. 
But that version is already about a year old, have there been any other releases not on github since then?

Switching to a monospace font would make it much more predictable to work with, if that would be an option?

**Comment by igrek51** [comment]
Actually, version in this public repository is a bit behind my official release. This is because after adding some changes I realized that I have my private API keys for some Android services there so I couldn't push it to public repository. I didn't figure out any decent solution yet, so I didn't push all things there (it would still stay in git history).

Please try to switch to latest v1.24.1 version - install it from here https://github.com/igrek51/android-songbook/releases/tag/v1.24.1 or from Google Play release and let me know if the issue is fixed there.

**Comment by chaptergy** [comment]
Ah, I've downloaded it via F-Droid (via IzzyOnDroid), so I was not aware that there were newer versions. But I've downloaded the version from Google Play and there it does work much better. Then I guess this is not an issue anymore. But it's a shame that these versions are not available via F-Droid.

**Comment by igrek51** [comment]
I'm glad it's working fine there. Thanks for your input. I'll try to sync up the master-branch repository as soon as I solve the API keys issue.
