### ISSUE TITLE
Possibilities in chords

### ISSUE THREAD

**Issue by theophany77** [igrek51/android-songbook#2]
Hi,

This is not an issue but rather a simple question and some comments.
I wonder if it is possible to manage such specific chords in your app :

> Dm7   G7   Cm  F#dim7

I played the guitar a few years ago with a teacher who taught me to play with music sheets then, quickly, with simple chords. 
I guess such chords as G7, Dm7, ... are too difficult to manage and that is why you mentioned in your ChordsTransposer.java "only" a few of them.
Still, I want to congratulate you for this nice app.
I am trying to learn how to develop with Android a songbook and I began searching for Phonegap books.
Then I found your app on Google play and it saved my day !
Just to know, why did you choose to develop under the native Android SDK rather than with a framework ?

Thank you.

Jean-michel

**Comment by igrek51** [comment]
The Chords Transposer is designed to manage chords like:

> G7, F#dim7, C#anyLetterOrNumber123

But the minor chords are parsed with a specific chords notation, where the format should be like this:

> not Dm7, but d7
> not Cm, but c

But it should not be so hard to handle also the "Dm" format, I'll add this to my ToDo list.

Warning: the chords are NOT represented with American notation, the consecutive sounds are:

> ... G G# A B H C C# ...
> not ... G G# A Bb B C C# ...

**Comment by igrek51** [comment]
Now, since version 1.1.17 application handles chords in both formats "Dm" and "d", these are example chords handled by application:

> d, d#, D, D#, Dm, D#m, Dmaj7, D#maj7, d7, d#7, D#m7, D#7, Dadd9, Dsus

Also there is a possibility to recognize chords in American notation, All you need is to change the array soundNames in class ChordsTransposer on your own.
Soon there should be possibility to enable it by the preferences in application.
