### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [igrek51/android-songbook#4]
Hi and first thanks for providing your app for free!

Would you consider also providing the APK in a place other than Google Play – for those unable to use the latter, or avoiding it for privacy reasons? Options for that would include getting it listed at [F-Droid](https://f-droid.org/), or simply attaching it to your `releases/` as many other projects do.

If you do consider that, I gladly assist with further steps if needed.

Thanks in advance!

**Comment by igrek51** [comment]
Hi,
I've put APK file for the latest release to the [release artifacts](https://github.com/igrek51/android-songbook/releases). I'll try to keep uploading APK files for each next release, though I'm reluctant to do so, because I can't track application errors, when it's not distributed by Google Play.

**Comment by IzzySoft** [comment]
Thanks a lot! I think that's a compromise worth it. "Us tin foils" is rather a small fraction of users, the majority will install your app via Google Play anyway – and be it only because Google injected them the idea that only installing from there is save (despite the fact that the only store were reportedly malware never was found is F-Droid).

To at least make sure those "tin foils" stand a chance to keep their installation of your app up-to-date, I'm adding it [here to my F-Droid repo](https://apt.izzysoft.de/fdroid/index/apk/igrek.songbook) (will show up behind that link with the next sync in about 12 hours): updates will appear there within 24h of your creating a new tag and attaching the `.apk` to it as you did now. If you wish, I can also help you getting it listed in the official F-Droid repo: my scanner just confirmed it should meet the strong inclusion criteria. Just let me know if you'd agree to that, and I'd file the packaging request (F-Droid would build the APK from source each time you tag a new release).

Thanks again – in the name of all the other "tin foils" :wink:
