### ISSUE TITLE
Last version adds a lot of AntiFeatures

### ISSUE THREAD

**Issue by IzzySoft** [igrek51/android-songbook#5]
Just saw v1.18.1 popping up with a bunch of trackers, almost doubling the size of the APK (compared to v1.14.0). Just wondering if that's an accident: What for does a Songbook app need Cloud messaging? I guess integrating FCM is also the reason that Firebase Analytics sneaked in.

Would you reconsider that move – or at least remove Firebase Analytics? Thanks in advance!

**Comment by igrek51** [comment]
Hi, I decided to use Firebase Crashlytics, because crashes reported by Google Play Console were pretty poor and I wasn't even able to get exception messages from there.
Firebase offers more verbose tools to report errors & crashes, but unfortunately even when I'm using just Crashlytics only (I'm not using Cloud messaging), that implies putting all Firebase & Google services libraries too in order to make it working.

I'm trying to put at least dependencies as possible to my APK, but unfortunately those libraries still need more and more. If you know a way how to make APK thinner, please let me know.

**Comment by IzzySoft** [comment]
Thanks for your fast response!

Firebase, Crashlytics etc. are libraries invading users' privacy – hence us tin-foils frown upon them. If you would consider some pricavy respecting crash reporters, you could e.g. take a look at [ACRA](https://github.com/ACRA/acra) or [tracedroid](https://github.com/ligi/tracedroid). Both leave the user the decision of sending the crash report after showing what will be sent – as opposed to those closed-source analytics tools you never can be sure what they grab along the path without even telling you (the developer).

Further, proprietary libraries taint your app: without them, your app would be fully FOSS. With them, it's only partly FOSS and thus loses trust (no blame to you, please don't get me wrong).

**Comment by igrek51** [comment]
In the latest APK I've removed some not needed libs, and due to some compression it got back to 4.32 MB, so I'm closing it

**Comment by IzzySoft** [comment]
Cool, thanks – quite a cleanup! Unfortunately, the AntiFeatures all remain.

**Comment by IzzySoft** [comment]
I just notice there are quite a load of proprietary, tracking libraries in the app meanwhile:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Google Ads (/com/google/ads): Ads
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Doubleclick (/com/google/android/gms/ads/doubleclick): Ads
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google API Client Libraries (/com/google/api/client): NonFreeNet
* Google Drive API (/com/google/api/services/drive): NonFreeDep,NonFreeNet
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): Tracking

9 offenders.
```

Is that intended? I thought you've slimmed this down: v1.18.1 had 4 offending libraries (and 7MB APK size); v1.19.1 had the offending libs down to 3 (and the APK size to 4MB – that was the time of my last comment above). Now, v1.24.1 has them up to 9 (and the size back at 7MB). Is that really needed? Then I'm afraid I have to unlist your app [from my repo](https://apt.izzysoft.de/fdroid/index/apk/igrek.songbook), as that's more than twice beyond the limit acceptable for proprietary/offending libraries.

**Comment by IzzySoft** [comment]
@igrek51 as you not responded, I have to unlist your app now. Once the issue is solved, I gladly put it up again – just give me a ping then. Thanks!
