### ISSUE TITLE
Display chord mapping for Ukulele (and probably other instruments)

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [igrek51/android-songbook#7]
At the moment, chords can only be displayed for guitar - which is kind of logic for a guitar songbook.

Anyway, it would be great to have the option to display the chords for other instruments, such as Ukulele, Harp or keyboard-based instruments too.

**Comment by igrek51** [comment]
Hi, Actually you can already display chord diagrams for Guitar, Ukulele and Mandolin. It should be available in settings to choose your instrument, then you'll see corresponding chords.

Take a look at the code, it's here: 
- https://github.com/igrek51/android-songbook/blob/a7838a0db1b37349710a342a9a1d890cc9b876ea/app/src/main/java/igrek/songbook/chords/diagram/ChordDiagramBuilder.kt#L15
- https://github.com/igrek51/android-songbook/blob/a7838a0db1b37349710a342a9a1d890cc9b876ea/app/src/main/java/igrek/songbook/chords/diagram/ChordsDiagrams.kt#L708
- https://github.com/igrek51/android-songbook/blob/a7838a0db1b37349710a342a9a1d890cc9b876ea/app/src/test/java/igrek/songbook/chords/diagram/UkuleleDiagramTest.kt#L14

I'd love to extend it with keyboard chords as you suggested, but honestly I don't have any data with keyboard chords in a structured form. Please keep in mind there's a plenty of chords, and I can't add them manually chord-by-chord. I don't even know them all, especially for instruments I can't even play.
So maybe you know some data source where these kind of chords are stored in a structured way. I would be grateful.
