### ISSUE TITLE
auto-play feature request

### ISSUE THREAD

**Issue by eplebel** [igrek51/android-songbook#8]
love this app, great stuff, one of the best out there!.

FEATURE REQUEST:
would be nice to have toggleable auto-play feature whereby at the end of a song, it auto-plays (while still auto-scrolling) to the next song in a setlist (or group of songs), as you already have with a swipe-right gesture.

**Comment by igrek51** [comment]
Good idea.
I've added forwarding songs automatically once autoscroll reaches the end. The countdown time before forwarding to a next song from a playlist depends on a autoscrolling speed, I guess it's most reasonable that way.

It is an optional feature in settings that is disabled by default.
Expect it to be in the next Songbook release soon.

**Comment by eplebel** [comment]
awesome, can't wait to try it out!

**Comment by eplebel** [comment]
p.s. are you associated with the [SongBookPro](https://songbook-pro.com/) app at all? (doesn't look like it)

**Comment by igrek51** [comment]
Nope, that's something completely different. just a coincidence of names

**Comment by eplebel** [comment]
ok i've now tried it out, very nice. and impressed how fast you were able to implement it, much much appreciated! 

re:  countdown time before auto-playing next song, any possibility to make this value user customizable? (i tried several different songs, and had to wait 30-31 seconds, which is a bit long)

SIDENOTE: my vision of this feature was to actually *SEE* the next song actually scroll up UNDERNEATH the current song, which would be even better UX, given one could get ready for the next song (what's the key, what capo? etc) while waiting for countdown tier (but this may be too ambitious based on your current implementation)
